# Dependencies
markdown:	kramdown
highlighter: rouge

# Permalinks
permalink:	/blog/:title

# Setup
title: WFortin
tagline:	'blog'
description:	'My personal blog.'
url:		http://wfortin.github.io

author:
  name:		'William Fortin'
  url:		https://twitter.com/willyfortin

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/willyfortin
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/wfortin
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://plus.google.com/+WilliamFortin
    desc:	Add me on google+

  - icon:	feed
    url:	http://wfortin.github.io/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about.html
    
copyright:
  author:	William Fortin
  url:		http://wfortin.github.io
  type_title:	All rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
